version: "3"

services:
  web:
    build:
      context: .
      args:
        - PROJECT_MODE
    volumes:
      - ./djangoweather:/app/
      - static:/static
    environment:
      - PYTHONUNBUFFERED=1
      - SHELL=/bin/bash
      - PROJECT_MODE
      - DJANGO_SECRET_KEY
      - ALLOWED_HOSTS
      - DEBUG
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_REGION_NAME
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    restart: unless-stopped
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static:
